//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranslateApp.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Word
    {
        public int Word_Id { get; set; }
        public string OriginalText { get; set; }
        public string TranslatedText { get; set; }
        public string FromLanguage { get; set; }
        public string ToLanguage { get; set; }
        public string PhoneticSymbols { get; set; }
        public string Notes { get; set; }
    
        public virtual Favorite Favorite { get; set; }
    }
}
